import type { MetadataRoute } from 'next';
import { SITE } from '@/lib/site';

/**
 * Web app manifest. Without one, an Android user who adds the site to their home screen
 * gets a screenshot-derived icon and the raw <title> as its label; with it they get the
 * brand mark and a short name that fits under an icon.
 *
 * `display: 'browser'` is deliberate. This is a website, not an installable app: the
 * standalone/fullscreen values strip the URL bar and back button, which is the wrong
 * trade for a travel guide people reach from search and share by link. Keeping it as
 * 'browser' means the manifest supplies the icon and name without changing how the site
 * behaves for anyone.
 *
 * Icons are generated by scripts/build-icons.mjs — never hand-edited.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE.name} - ${SITE.tagline}`,
    short_name: 'Bondi Beach',
    description: SITE.description,
    start_url: '/',
    display: 'browser',
    // Matches the icon tile, so the splash/theme surfaces are the same teal as the mark.
    theme_color: '#186576',
    background_color: '#faf7f2', // sand-50, the site background
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
}
